# Generated by Django 4.0.5 on 2022-06-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0002_alter_exercise_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
